#!/bin/bash
set -e

commit="d8887bc8ce14a47d5b9d45f6697f05d53e43fe9a"
source="https://raw.githubusercontent.com/linux-surface/linux-surface/${commit}/pkg/keys/surface.cer"

basedir=$(dirname "${0}")
cd "${basedir}"

wget -O "surface.cer" ${source}

dpkg-buildpackage -b
