#!/bin/bash
set -e

pre_remove() {
    echo ""
    echo "The following secure-boot certificate will be uninstalled and revoked from"
    echo "your system"
    echo ""
    echo "    /usr/share/linux-surface-secureboot/surface.cer"
    echo ""

    local hashfile=$(mktemp)
    mokutil --generate-hash=surface > ${hashfile}
    mokutil --hash-file ${hashfile} --delete /usr/share/linux-surface-secureboot/surface.cer

    echo "The key will be revoked on the next start of your system. You will then"
    echo "again asked for the password. Enter 'surface' to confirm."
    echo ""
    echo "Kernels signed with the corresponding private key will still not be allowed"
    echo "to boot after this. Note that you can always manage your secure-boot keys"
    echo "via the 'mokutil' tool. Please refer to 'man mokutil' for more information."
    echo ""
}

pre_upgrade() {
    local backup="/tmp/linux-surface-secureboot.surface.cer.backup"
    local original="/usr/share/linux-surface-secureboot/surface.cer"

    cp "${original}" "${backup}"
}

if [[ "${1}" == "remove" ]]; then
    pre_remove
    exit 0
fi

if [[ "${1}" == "upgrade" ]]; then
    pre_upgrade
    exit 0
fi
